Additional encoding fix for use with formataddr() in subscription approval.
Case CPANEL-47086: A previous fix to decode name into a str before
feeding it into formataddr() needed to also be applied to 2 other
calls to formataddr().

Changelog: Mailman subscription approval: Fix AttributeError
  'bytes' object has no attribute 'encode'.